INSERT INTO STOCK(ID,COMPANY_NAME,STOCK_PRICE)values(101,'tata',1000);
INSERT INTO STOCK(ID,COMPANY_NAME,STOCK_PRICE)values(102,'techm',1200);
INSERT INTO STOCK(ID,COMPANY_NAME,STOCK_PRICE)values(103,'amdocs',900);
INSERT INTO STOCK(ID,COMPANY_NAME,STOCK_PRICE)values(104,'citibank',400);